import { Application } from '../shared/components/application/application.component';
import './global.css';

export const metadata = {
  title: 'Welcome to apps/my-new-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Application>{children}</Application>
      </body>
    </html>
  );
}
